name       : lerna
version    : 3.15.0
release    : 4
source     :
    - https://github.com/lerna/lerna/archive/v3.15.0.tar.gz : 64c96bbefa369741a9fb631db3452e09f0aad9fd5fe936152fd1f15bdb867ea7
license    : MIT
component  : programming.tools
summary    : Manage JavaScript projects with multiple packages
description: |
    A Tool for managing JavaScript projects with multiple packages
networking : yes
builddeps  :
    - yarn
rundeps    :
    - nodejs
setup      : |
    yarn
install    : |
    install -dm00644 $installdir/usr/bin
    install -dm00644 $installdir/usr/lib/node_modules/lerna
    cp -R node_modules yarn.lock package.json $installdir/usr/lib/node_modules/lerna/
    ln -s /usr/lib/node_modules/lerna/node_modules/.bin/lerna $installdir/usr/bin/lerna
