name       : lerna
version    : 3.11.1
release    : 3
source     :
    - https://github.com/lerna/lerna/archive/v3.11.1.tar.gz : 0c4f31780d4c3bb37aaed633e6863cc69a1a9b367e7816f13bb19ba4c62541a6
license    : MIT
component  : programming.tools
summary    : Manage JavaScript projects with multiple packages
description: |
    A Tool for managing JavaScript projects with multiple packages
networking : yes
builddeps  :
    - yarn
rundeps    :
    - nodejs
setup      : |
    yarn
install    : |
    install -dm00644 $installdir/usr/bin
    install -dm00644 $installdir/usr/lib/node_modules/lerna
    cp -R node_modules yarn.lock package.json $installdir/usr/lib/node_modules/lerna/
    ln -s /usr/lib/node_modules/lerna/node_modules/.bin/lerna $installdir/usr/bin/lerna
